version: "3.9"

services:

  perlite:
    image: allotment-app
    environment:
      - HIDE_FOLDERS=docs,private,trash

  web:
    image: allotment-web
    ports:
      - 8080:80     
    depends_on:
      - perlite

  

