version: "3.9"

services:

  perlite:
    image: ghcr.io/philskents/allotment-manager/app:latest
    environment:
      - HIDE_FOLDERS=docs,private,trash

  web:
    image: ghcr.io/philskents/allotment-manager/web:latest
    ports:
      - 8080:80     
    depends_on:
      - perlite

  

