FROM nginx:latest

MAINTAINER sec77 https://github.com/secure-77/Perlite

RUN rm /etc/nginx/conf.d/default.conf 
COPY ./Perlite/web/config/ /etc/nginx/conf.d/
COPY ./Perlite/web/ratty-launch.sh ./

WORKDIR /var/www/perlite/
COPY ./Perlite/perlite/*.php ./
COPY ./Perlite/perlite/*.ico ./
COPY ./Perlite/perlite/*.svg ./
COPY ./Perlite/perlite/.styles/* ./.styles/
COPY ./Perlite/perlite/.js/* ./.js/
COPY ./allotments/ ./
EXPOSE 80
